language: python
python: 2.7
os: linux
dist: xenial

version: ~> 1.0

# Install docker service dependencies.
services:
- docker

# Update docker.
addons:
  apt:
    packages:
      - docker-ce

install:
  - docker --version
  - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}

script:
- ROS_IMAGE_VERSION=kinetic-ros-base-xenial-`echo ${TRAVIS_PULL_REQUEST_BRANCH:=${TRAVIS_BRANCH}} | sed 's/\//-/g'` make uploadImage

branches:
  only:
    - /release.*/
