language: python
python: 2.7

sudo: required

services:
- docker

env:
  global:
    - secure: S+E9yqbLJo71qqeRtOVLMSdY4RJ/2yzJBymDa/TK9eRofEy96oJ5Ltpbyb3Zyx9PMAOlP1I+DoTfS9KQW8bDRZHyLFUCmZLRQ6jTQJL0Xf87LEKsSXwPqsb6bzZnoSYPJz33KjLyZX+YCtRrANDJyvhzHJFLQV871TxJHYZxY0c59HlsCIaAyUe1XrF63bmXTTTONosYlSaXQzChrs6bL2V2xP5C3WJZMjkG2wN/L/8qix+2Xki7jyKcR7aIcRcpw7SxRZBeBodkDxEVlNHdSu/ud+qiq3pc8VXA5yVuKj31JkZzOnmHEaA/G9Fpr8qnxS6SiHFTWDy/xfKqfqvI6MGmIcLGTBlYtdyfokBIW9lE0vDbxZm4WKRjBPUeuGxYnm+bT3z1gYE8DlyB75CyesvCc1aU+GIBpiMK/FxesTxGjO+SSqtVlk94BTEmKeBjcHpcibDAtPU/lUQc205dJ35f8w4Jn582nOyxCiQ4b3ssIEQTyuimVAPE8uLkHdMiqZLSSoqH0AotRAVHynXB44sPneucKV2ELLpj7ZXeIsGSFGujz9SfpZRDsuXKSGSn916ZW4hvgKkaQcLn7DJqtPBP6jd60mvSqr1qmvKU8LGZXCkPKvFSUeeE576u3xT2dkLCmTmhfZYKUws/N2UookxVNx376uY1LM7Wi0KxC1I=
    - secure: seZdS0NO9RAk4g2w597+rkT+rREYfVbwcnqRk8Jdm+9LC6bnTPby5pVXFLFWnSNk/ZjtDjVYStxe1yRM9gFkY/wukkLKF88e5lrJP9/u0twnFdnHY1rKYKWIZwmli65pSRo7WfjO/u7Qz5621LhcBvmSXMB2QVDEsdBOcWwaUGsh9As7sZdk93zVaZoXW5Bo0Y4Z4asLxSUKp7tPKHbBWwWDL3jk8q+p4gTu6TStI0y/xsEnpxxvADdvVwtGAtxpwyXvry2shIUvnK6CfRjLRl9jZEnMoXxW5UBi2lA/2HR3YVY3+bvP/e6WwckD1ICMr/ZjMh1X1ELnMtMj7aoOIbjK1hviveXag3Y5Z4QLTKJAih6qSUE9f0VLIYpXpPJQAD8jo/9Q86EXhiBq8zE6xoVTYkPEChkY0Bcla9cep0CldLivmi85r6e5X92QtlLDTlGS5Ehzfw98D4kbFs88uKdh1UQD8QbxMgLn8RmVjUPaJ81XyEB/MVZGCCsal1+AdkOpb/qQ8qRSWs1TbL/7BA/R/CbGv39Azcc8myUu0DBbSQs6xWn91Qf4KRx4M0MCJ6GIKEdj29ZhaidIoeBeLcsEka8UUe0hpsmYSVhjTU3jMQra3cZgxykaP8ZUGsC5rv0i4sWHLGZR4nbapQt9wMRg9NNUFy62tbJ2uwdXcNU=

install:
  - docker login --user ${DOCKER_USER} --password ${DOCKER_PASSWORD}

script:
- make uploadImage

branches:
  only:
    - master

notifications:
  slack:
    secure: ks1aBCYZA1/LJXEQNj17K1ucNMjoH9LtfTEq18hpcpcP4oYKaUykGi6gqdkm7BOriaNPraMRMwkBa6xxJeTl5xbO/ySgOSdA/VlGkRGULhnDr8pl2nU+K8ls8Rx2vlSv7OqvvZG5sXK0VZ5RNIZa/j88wZ0YIxzBu59TvV9aP5A7jEZB1JfDpg9NAdubU5RCEFrdnoeTVu+whJJGtx/lV0+Nvqen8KxgPrwJ2sZXy1XUSOd07tfUdLsSyCUGTJiw4SHEwf4lbsgtLgHdyJR+JfX/v7J6XUab64ZwZEUZLw3L2E4+RZ2/xbDqD2nvRB4s26dv7K8jNsV9t9/gY7dz7t1HeMhfFgH3/LJMWdWPHcspbb//yvcLsOcDIfjRbIFDvxSQav6k7PY0IR+HqH9uztpHEWnncVJZ+tpcWWh3z3Y+yaN7x3IK14BFQ1D65Wl1k5THrG0DQXmh3Z65u4wdIsuxxEAZULvKSUQ8S+l/vbnW522mxV5jVRfTVDswh9SCE2PXGF+qlcMyaK/4/S5HqIyjYfaLJvs+Fi49dicglXJs6AYKfhkm3pLZMYW5VpDP+8qAkhqc0uYLLKTDqXTu46sW93UkFHJ/UYJLLsbpZ4/9kmos2APcxrhMZN/vf6NBopDSByRvYB8oXTHO3grOdTnkF2MSyJ6GI214SdgKaVw=
