language: python
python: 2.7
os: linux
dist: xenial

version: ~> 1.0

services:
- docker

install:
  - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}

script:
- BRANCH=${TRAVIS_BRANCH} make uploadImage

branches:
  only:
    - /release.*/
